///////////////////
// AUTO GENERATED by setupStories.ts
///////////////////

/** Provides stories to storybook web config */
module.exports = [
  '../storybook/stories/base/ActivityIndicator.stories',
  '../storybook/stories/base/Box.stories',
  '../storybook/stories/base/Text.stories',
  '../storybook/stories/composite/Icon.stories',
  '../storybook/stories/composite/InputText.stories',
  '../storybook/stories/sample/Button.stories',
  '../storybook/stories/sample/Welcome.stories',
]

