///////////////////
// AUTO GENERATED by setupStories.ts
// Import loadStories in storybook/index.ts and execute in the configure function execution.
///////////////////

export const loadStories = () => {
  require('./stories/base/ActivityIndicator.stories.tsx')
  require('./stories/base/Box.stories.tsx')
  require('./stories/base/Card.stories.tsx')
  require('./stories/base/Text.stories.tsx')
  require('./stories/composite/ButtonInnner.stories.tsx')
  require('./stories/composite/ButtonMain.stories.tsx')
  require('./stories/composite/Icon.stories.tsx')
  require('./stories/composite/InputText.stories.tsx')
  require('./stories/sample/Button.stories.tsx')
  require('./stories/sample/Welcome.stories.tsx')
}
