///////////////////
// AUTO GENERATED by setupStories.ts
// Import loadStories in storybook/index.ts and execute in the configure function execution.
///////////////////

export const loadStories = () => {
  require('./stories/base/Box.stories')
  require('./stories/base/Text.stories')
  require('./stories/composite/Icon.stories')
  require('./stories/sample/Button.stories')
  require('./stories/sample/Welcome.stories')
}
